
BLENDER="C:\Program Files\Blender Foundation\Blender 2.93\blender.exe"
DIST=../dist

all : \
    $(DIST)/city.pnct \
    $(DIST)/city.scene \

$(DIST)/city.scene : city.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "city.blend:Scene" "$(DIST)/city.scene"

$(DIST)/city.pnct : city.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "city.blend:Scene" "$(DIST)/city.pnct" 
